### ISSUE TITLE
app_label and isn't in an application in INSTALLED_APPS.

### ISSUE THREAD

**Issue by Austrotaxus** [aechiara/aa-industry#2]
Hello.

Trying to install your plugin to my AA hosted on the local host. However i cannot migrate with the following error

`Traceback (most recent call last):
  File "/home/allianceserver/hospauth/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/apps/config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/industry/models.py", line 7, in <module>
    from eveuniverse.models import EveSolarSystem
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/eveuniverse/models.py", line 361, in <module>
    class EveEntity(EveUniverseEntityModel):
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/db/models/base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class eveuniverse.models.EveEntity doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

I have added 'industry' to the local.py in the settings dir:

`INSTALLED_APPS += [
    'corptools',
    'industry',
]
`

**Comment by Austrotaxus** [comment]
Adding 'eveuniverse' to the INSTALLED_APPS did the job
